version: "3.9"

services:
  postgres:
    container_name: "cloud-storage-postgres"
    image: postgres:latest
    restart: always
    volumes:
      - db_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
      POSTGRES_DB: cloud-storage-db
    ports:
      - '5433:5432'

volumes:
  db_storage: